Milestone 1: Add classes
Rachelwebdev/school-library-OOP pull request #1
Opened 2023-04-10 15:10 UTC by Rachelwebdev

### In this Milestone, I;

- Created a class `Person` with getters, setters, and methods

- Created a class `Student` which inherits from `Person` and has a method `play_hooky`

- Created a class `Teacher`which inherits from `Person`

2023-04-10 15:13 UTC, julie-ify commented
Hi @Rachelwebdev,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your linter checks failed and you do not have a descriptive readme file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-10 19:02 UTC, danmainah requested changes
Hi @Rachelwebdev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-10 19:02 UTC, danmainah commented on person.rb
> +  def of_age?
- [ ] @Rachelwebdev great work on your method however the name is wrong kindly change it to `is_of_age` as it is in the project description
![image](https://user-images.githubusercontent.com/61408860/230973294-9d60136e-4fca-4e0d-9a73-0727501d0730.png)

2023-04-11 02:01 UTC, Rachelwebdev commented on person.rb
> +  def of_age?
Thanks, I will made the change

2023-04-11 02:19 UTC, Ismailco approved these changes
### Hi @Rachelwebdev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 06:21 UTC, Rachelwebdev commented
Thanks for the approval

2023-04-11 06:22 UTC, merged